### PR TITLE
feat: Log metrics and executions details for ETL Tool

### PR DESCRIPTION
**Pull request by marcionemec-daitan**
# Description

Store volumetry and time metrics to detect anomalies or identify performance gaps in steps of each process.
Store execution status (Success or failure)

Fixes # (73)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Unit test
- [x] Execute use cases for Success and failures

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

### CODE REVIEW

**Comment by marcionemec-daitan** [comment]
@DerekRoberts , any actions to be taken regarding the "PR / Deploy / Deploy (pull_request)" action or is it good to go?

**Comment by DerekRoberts** [comment]
@marcionemec-daitan It appears to be dead!  We can fix this tomorrow.  Hope the weekend has been otherwise good to you.  :)

**Comment by DerekRoberts** [comment]
@marcionemec-daitan Got it!  :)

**Comment by marcionemec-daitan** [comment]
Including unit test screenshot based on logs of 2 processes:

image

**Comment by marcionemec-daitan** [comment]
@DerekRoberts Thank you! I had a nice weekend. Hope you too! =)

**Review by DerekRoberts — APPROVED** [review]

**Pull request merged**
